### ISSUE TITLE
Echo on Sending Encrypted voice

### ISSUE THREAD

**Issue by Miracle-doctor** [gegel/jackpair#2]

**Comment by Miroqil** [comment]
Is this project full developed or some parts developed?

**Comment by gegel** [comment]
See quectel guide for tune M66 (in attachment).

Try this set of audio parameters:


AT+QAPS=1,4,1, "0.0.32512.65535.0.0.65535.65535.65535.0.0.0.0.0.0.0"
AT+QAPS=1,4,1, "0.0.32512.0.0.0.0.15.0.0.0.0.32513.0.0.0"  

This was find empirically. You can also try change parameters with this QAPS during a call (on-the-fly) and check audio on the other side (this parameters affect mostly TX but also partially RX).
If you find more best parameters, please tell me.

And use:
AT+QAUDCH=1
AT+QSIDET=0
AT+QSFR=1
AT+CAGC=0,0

for select audio channel, disable side tone, select preffered codec GSM FR and disable AGC.

Information about audio parameters are closed by MTK, but you can read some info here:

Commands are responsible for sound settings and they are equivalent commands, but it is recommended to use QAPS command The syntax of QAPS command. AT+QAPS=1,4,,”...............” Params are pesponsible for: 0-2, 12: Acoustic echo control 3-6, 8-11 : Noise and dynamic range control 7: digital gain 13-14: Dual microphone noise reduction 15: N\A

https://stackoverflow.com/questions/38719813/at-command-atqasp-ateasp

http://www.docx88.com/wkid-22ec1de90342a8956bec0975f46527d3240ca683-1.html
http://www.docx88.com/wkid-c3e5fa776c175f0e7cd137cb-1.html


In MTK smartphones you can change audio parameters from engineering menu ( enter code is *#*#3646633#*#*), see also https://forum.xda-developers.com/showthread.php?t=2248396

Also some refs:

https://wenku.baidu.com/view/22ec1de90342a8956bec0975f46527d3240ca683.html?re=view
https://wenku.baidu.com/view/abf537db50e2524de5187ee8.html

Speech_Function_User_Manual_百度文库

https://wenku.baidu.com/view/abf537db50e2524de5187ee8.html


BR, Van. 
21 December 2018, 09:59:09, by Miracle <notifications@github.com>:

Is this project full developed or some parts developed?

**Comment by gegel** [comment]
Full for now: see http://torfone.org/jackpair/   and you can download all parts (source, firmware and windows exe) from page menu.

BR, VAN


21 December 2018, 09:59:09, by Miracle <notifications@github.com>:

Is this project full developed or some parts developed?

**Comment by gegel** [comment]
21 December 2018, 09:59:09, by Miracle <notifications@github.com>:

Is this project full developed or some parts developed?

**Comment by Miracle-doctor** [comment]
I solve this problem by using some tweeks. Thanks!
